Change multiplication proof and add P!=Q constraint
cloudflare/zkp-ecdsa pull request #4
Opened 2021-11-23 07:33 UTC by 3for

1) Change multiplication proof: the algorithm in [Doubly-efficient zkSNARKs without trusted setup](https://eprint.iacr.org/2017/1132.pdf) Figure 5 is more efficient. 
2) For the realization of point addition proof in this repo, `P!=Q` constraint should be added.

2021-12-06 03:42 UTC, wbl reviewed
We'd prefer this be recast as two commits and not make so many spurious changes. That's really the only comment I have. Thank you for your interest in contributing!

2021-12-06 03:43 UTC, wbl requested changes
Alas I misclicked so now I have to write this comment explaining that needs to be changed before merging.

2021-12-06 04:14 UTC, 3for commented on src/commit/mult.ts
> +        //C_4: Group.Point,
Sorry for the unclean code. Because I commit the code and test in another machine. Maybe I can make a clean version or you can just change the code?

2021-12-07 02:32 UTC, wbl commented on src/commit/mult.ts
> +        //C_4: Group.Point,
We'd appreciate a clean version. That's really the only issue here, assuming the proof works.

2021-12-07 07:15 UTC, closed without merging

2021-12-07 07:43 UTC, 3for commented
See the clean version #5 .